build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank Loan related QA APIs "
  contactDetails:
    name: "Loan Singh - QA Lead"
    email: "Loan@eazybank.com"
  onCallSupport:
    - (666) 265-222342
    - (666) 734-111678